
package exer13;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ImagemServicoImpService", targetNamespace = "http://exer12/", wsdlLocation = "http://127.0.0.1:9091/imagem?wsdl")
public class ImagemServicoImpService
    extends Service
{

    private final static URL IMAGEMSERVICOIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMAGEMSERVICOIMPSERVICE_EXCEPTION;
    private final static QName IMAGEMSERVICOIMPSERVICE_QNAME = new QName("http://exer12/", "ImagemServicoImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9091/imagem?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMAGEMSERVICOIMPSERVICE_WSDL_LOCATION = url;
        IMAGEMSERVICOIMPSERVICE_EXCEPTION = e;
    }

    public ImagemServicoImpService() {
        super(__getWsdlLocation(), IMAGEMSERVICOIMPSERVICE_QNAME);
    }

    public ImagemServicoImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMAGEMSERVICOIMPSERVICE_QNAME, features);
    }

    public ImagemServicoImpService(URL wsdlLocation) {
        super(wsdlLocation, IMAGEMSERVICOIMPSERVICE_QNAME);
    }

    public ImagemServicoImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMAGEMSERVICOIMPSERVICE_QNAME, features);
    }

    public ImagemServicoImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImagemServicoImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicoImagem
     */
    @WebEndpoint(name = "ImagemServicoImpPort")
    public ServicoImagem getImagemServicoImpPort() {
        return super.getPort(new QName("http://exer12/", "ImagemServicoImpPort"), ServicoImagem.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicoImagem
     */
    @WebEndpoint(name = "ImagemServicoImpPort")
    public ServicoImagem getImagemServicoImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://exer12/", "ImagemServicoImpPort"), ServicoImagem.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMAGEMSERVICOIMPSERVICE_EXCEPTION!= null) {
            throw IMAGEMSERVICOIMPSERVICE_EXCEPTION;
        }
        return IMAGEMSERVICOIMPSERVICE_WSDL_LOCATION;
    }

}
