
package exer13;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicoImagem", targetNamespace = "http://exer12/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicoImagem {


    /**
     * 
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dowload", targetNamespace = "http://exer12/", className = "exer12.Dowload")
    @ResponseWrapper(localName = "dowloadResponse", targetNamespace = "http://exer12/", className = "exer12.DowloadResponse")
    @Action(input = "http://exer12/ServicoImagem/dowloadRequest", output = "http://exer12/ServicoImagem/dowloadResponse")
    public byte[] dowload();

}
