
package exer2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculadoraImpService", targetNamespace = "http://exer1/", wsdlLocation = "http://127.0.0.1:9090/calculadora?wsdl")
public class CalculadoraImpService
    extends Service
{

    private final static URL CALCULADORAIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULADORAIMPSERVICE_EXCEPTION;
    private final static QName CALCULADORAIMPSERVICE_QNAME = new QName("http://exer1/", "CalculadoraImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9090/calculadora?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULADORAIMPSERVICE_WSDL_LOCATION = url;
        CALCULADORAIMPSERVICE_EXCEPTION = e;
    }

    public CalculadoraImpService() {
        super(__getWsdlLocation(), CALCULADORAIMPSERVICE_QNAME);
    }

    public CalculadoraImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULADORAIMPSERVICE_QNAME, features);
    }

    public CalculadoraImpService(URL wsdlLocation) {
        super(wsdlLocation, CALCULADORAIMPSERVICE_QNAME);
    }

    public CalculadoraImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULADORAIMPSERVICE_QNAME, features);
    }

    public CalculadoraImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Calculadora
     */
    @WebEndpoint(name = "CalculadoraImpPort")
    public Calculadora getCalculadoraImpPort() {
        return super.getPort(new QName("http://exer1/", "CalculadoraImpPort"), Calculadora.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Calculadora
     */
    @WebEndpoint(name = "CalculadoraImpPort")
    public Calculadora getCalculadoraImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://exer1/", "CalculadoraImpPort"), Calculadora.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULADORAIMPSERVICE_EXCEPTION!= null) {
            throw CALCULADORAIMPSERVICE_EXCEPTION;
        }
        return CALCULADORAIMPSERVICE_WSDL_LOCATION;
    }

}
