
package exer11;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContatoImpService", targetNamespace = "http://exer10/", wsdlLocation = "http://127.0.0.1:9091/contatos?wsdl")
public class ContatoImpService
    extends Service
{

    private final static URL CONTATOIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTATOIMPSERVICE_EXCEPTION;
    private final static QName CONTATOIMPSERVICE_QNAME = new QName("http://exer10/", "ContatoImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9091/contatos?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTATOIMPSERVICE_WSDL_LOCATION = url;
        CONTATOIMPSERVICE_EXCEPTION = e;
    }

    public ContatoImpService() {
        super(__getWsdlLocation(), CONTATOIMPSERVICE_QNAME);
    }

    public ContatoImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTATOIMPSERVICE_QNAME, features);
    }

    public ContatoImpService(URL wsdlLocation) {
        super(wsdlLocation, CONTATOIMPSERVICE_QNAME);
    }

    public ContatoImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTATOIMPSERVICE_QNAME, features);
    }

    public ContatoImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContatoImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Telefone
     */
    @WebEndpoint(name = "ContatoImpPort")
    public Telefone getContatoImpPort() {
        return super.getPort(new QName("http://exer10/", "ContatoImpPort"), Telefone.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Telefone
     */
    @WebEndpoint(name = "ContatoImpPort")
    public Telefone getContatoImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://exer10/", "ContatoImpPort"), Telefone.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTATOIMPSERVICE_EXCEPTION!= null) {
            throw CONTATOIMPSERVICE_EXCEPTION;
        }
        return CONTATOIMPSERVICE_WSDL_LOCATION;
    }

}
