
package exer11;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Telefone", targetNamespace = "http://exer10/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Telefone {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "adicionar", targetNamespace = "http://exer10/", className = "exer11.Adicionar")
    @ResponseWrapper(localName = "adicionarResponse", targetNamespace = "http://exer10/", className = "exer11.AdicionarResponse")
    @Action(input = "http://exer10/Telefone/adicionarRequest", output = "http://exer10/Telefone/adicionarResponse")
    public void adicionar(
        @WebParam(name = "arg0", targetNamespace = "")
        Contato arg0);

    /**
     * 
     * @return
     *     returns java.util.List<exer11.Contato>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContatos", targetNamespace = "http://exer10/", className = "exer11.GetContatos")
    @ResponseWrapper(localName = "getContatosResponse", targetNamespace = "http://exer10/", className = "exer11.GetContatosResponse")
    @Action(input = "http://exer10/Telefone/getContatosRequest", output = "http://exer10/Telefone/getContatosResponse")
    public List<Contato> getContatos();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deletar", targetNamespace = "http://exer10/", className = "exer11.Deletar")
    @ResponseWrapper(localName = "deletarResponse", targetNamespace = "http://exer10/", className = "exer11.DeletarResponse")
    @Action(input = "http://exer10/Telefone/deletarRequest", output = "http://exer10/Telefone/deletarResponse")
    public void deletar(
        @WebParam(name = "arg0", targetNamespace = "")
        Contato arg0);

}
