
package exer6;

import java.math.BigDecimal;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CartaoVisa", targetNamespace = "http://visa.eletron.consulta")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CartaoVisa {


    /**
     * 
     * @param arg0
     * @return
     *     returns exer6.Consulta
     */
    @WebMethod
    @WebResult(name = "resultadoConsulta", targetNamespace = "")
    @RequestWrapper(localName = "operacaoDebitarSaldo", targetNamespace = "http://visa.eletron.consulta", className = "exer6.OperacaoDebitarSaldo")
    @ResponseWrapper(localName = "operacaoDebitarSaldoResponse", targetNamespace = "http://visa.eletron.consulta", className = "exer6.OperacaoDebitarSaldoResponse")
    @Action(input = "http://visa.eletron.consulta/CartaoVisa/operacaoDebitarSaldoRequest", output = "http://visa.eletron.consulta/CartaoVisa/operacaoDebitarSaldoResponse")
    public Consulta operacaoDebitarSaldo(
        @WebParam(name = "arg0", targetNamespace = "")
        BigDecimal arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "operacaoCreditarSaldo", targetNamespace = "http://visa.eletron.consulta", className = "exer6.OperacaoCreditarSaldo")
    @Action(input = "http://visa.eletron.consulta/CartaoVisa/operacaoCreditarSaldo")
    public void operacaoCreditarSaldo(
        @WebParam(name = "arg0", targetNamespace = "")
        BigDecimal arg0);

}
