
package exer15;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Venda", targetNamespace = "http://exer14/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Venda {


    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "vender", targetNamespace = "http://exer14/", className = "exer15.Vender")
    @ResponseWrapper(localName = "venderResponse", targetNamespace = "http://exer14/", className = "exer15.VenderResponse")
    @Action(input = "http://exer14/Venda/venderRequest", output = "http://exer14/Venda/venderResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://exer14/Venda/vender/Fault/Exception")
    })
    public void vender(
        @WebParam(name = "arg0", targetNamespace = "")
        Produto arg0)
        throws Exception_Exception
    ;

}
