
package exer15;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VendaImpService", targetNamespace = "http://exer14/", wsdlLocation = "http://127.0.0.1:9091/venda?wsdl")
public class VendaImpService
    extends Service
{

    private final static URL VENDAIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException VENDAIMPSERVICE_EXCEPTION;
    private final static QName VENDAIMPSERVICE_QNAME = new QName("http://exer14/", "VendaImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9091/venda?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VENDAIMPSERVICE_WSDL_LOCATION = url;
        VENDAIMPSERVICE_EXCEPTION = e;
    }

    public VendaImpService() {
        super(__getWsdlLocation(), VENDAIMPSERVICE_QNAME);
    }

    public VendaImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VENDAIMPSERVICE_QNAME, features);
    }

    public VendaImpService(URL wsdlLocation) {
        super(wsdlLocation, VENDAIMPSERVICE_QNAME);
    }

    public VendaImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VENDAIMPSERVICE_QNAME, features);
    }

    public VendaImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VendaImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Venda
     */
    @WebEndpoint(name = "VendaImpPort")
    public Venda getVendaImpPort() {
        return super.getPort(new QName("http://exer14/", "VendaImpPort"), Venda.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Venda
     */
    @WebEndpoint(name = "VendaImpPort")
    public Venda getVendaImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://exer14/", "VendaImpPort"), Venda.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VENDAIMPSERVICE_EXCEPTION!= null) {
            throw VENDAIMPSERVICE_EXCEPTION;
        }
        return VENDAIMPSERVICE_WSDL_LOCATION;
    }

}
