
package exer8;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataHoraImpService", targetNamespace = "http://exer7/", wsdlLocation = "http://127.0.0.1:9091/datahora?wsdl")
public class DataHoraImpService
    extends Service
{

    private final static URL DATAHORAIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException DATAHORAIMPSERVICE_EXCEPTION;
    private final static QName DATAHORAIMPSERVICE_QNAME = new QName("http://exer7/", "DataHoraImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9091/datahora?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATAHORAIMPSERVICE_WSDL_LOCATION = url;
        DATAHORAIMPSERVICE_EXCEPTION = e;
    }

    public DataHoraImpService() {
        super(__getWsdlLocation(), DATAHORAIMPSERVICE_QNAME);
    }

    public DataHoraImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATAHORAIMPSERVICE_QNAME, features);
    }

    public DataHoraImpService(URL wsdlLocation) {
        super(wsdlLocation, DATAHORAIMPSERVICE_QNAME);
    }

    public DataHoraImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATAHORAIMPSERVICE_QNAME, features);
    }

    public DataHoraImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataHoraImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DataHora
     */
    @WebEndpoint(name = "DataHoraImpPort")
    public DataHora getDataHoraImpPort() {
        return super.getPort(new QName("http://exer7/", "DataHoraImpPort"), DataHora.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataHora
     */
    @WebEndpoint(name = "DataHoraImpPort")
    public DataHora getDataHoraImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://exer7/", "DataHoraImpPort"), DataHora.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATAHORAIMPSERVICE_EXCEPTION!= null) {
            throw DATAHORAIMPSERVICE_EXCEPTION;
        }
        return DATAHORAIMPSERVICE_WSDL_LOCATION;
    }

}
