
package exer3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LivrariaOnline", targetNamespace = "http://exer3/", wsdlLocation = "http://127.0.0.1:9090/livraria?wsdl")
public class LivrariaOnline
    extends Service
{

    private final static URL LIVRARIAONLINE_WSDL_LOCATION;
    private final static WebServiceException LIVRARIAONLINE_EXCEPTION;
    private final static QName LIVRARIAONLINE_QNAME = new QName("http://exer3/", "LivrariaOnline");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9090/livraria?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIVRARIAONLINE_WSDL_LOCATION = url;
        LIVRARIAONLINE_EXCEPTION = e;
    }

    public LivrariaOnline() {
        super(__getWsdlLocation(), LIVRARIAONLINE_QNAME);
    }

    public LivrariaOnline(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIVRARIAONLINE_QNAME, features);
    }

    public LivrariaOnline(URL wsdlLocation) {
        super(wsdlLocation, LIVRARIAONLINE_QNAME);
    }

    public LivrariaOnline(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIVRARIAONLINE_QNAME, features);
    }

    public LivrariaOnline(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LivrariaOnline(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Livraria
     */
    @WebEndpoint(name = "LivrariaImpPort")
    public Livraria getLivrariaImpPort() {
        return super.getPort(new QName("http://exer3/", "LivrariaImpPort"), Livraria.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Livraria
     */
    @WebEndpoint(name = "LivrariaImpPort")
    public Livraria getLivrariaImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://exer3/", "LivrariaImpPort"), Livraria.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIVRARIAONLINE_EXCEPTION!= null) {
            throw LIVRARIAONLINE_EXCEPTION;
        }
        return LIVRARIAONLINE_WSDL_LOCATION;
    }

}
